name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-26

    steps:
    - uses: actions/checkout@v4
    - name: Check out the build submodules
      run: |
        git submodule update --init \
          lib/libbsdmalloc \
          lib/libsbuf \
          lib/libkext
    - name: make ARCH=arm64e
      run: make ARCH=arm64e
    - name: make ARCH=x86_64
      run: make ARCH=x86_64
    - name: make ARCH=universal
      run: make ARCH=universal
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
